name: Build & Publish

on:
  push:
    branches: [ "main", "feat/initial-version" ]
  pull_request:
    branches: [ "main" ]
env:
  NODE_VERSION: 18

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    - name: Cache node_modules
      id: npm-cache
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: npm-${{ env.NODE_VERSION }}-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-${{ env.NODE_VERSION }}-
    - run: npm ci
      if: steps.npm-cache.outputs.cache-hit != 'true'
    - run: npm run build --if-present
  Test:
    runs-on: ubuntu-latest
    needs: ["Build"]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    - name: Cache node_modules
      id: npm-cache
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: npm-${{ env.NODE_VERSION }}-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-${{ env.NODE_VERSION }}-
    - run: npm ci
      if: steps.npm-cache.outputs.cache-hit != 'true'
    - run: npm test