name: Build & Publish

on:
  push:
    branches: [ "main", "feat/initial-version" ]
  pull_request:
    branches: [ "main" ]
env:
  NODE_VERSION: 18

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    - name: Cache node_modules
      id: npm-cache
      uses: actions/cache@v4
      with:
        path: ./node_modules
        key: npm-${{ env.NODE_VERSION }}-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-${{ env.NODE_VERSION }}-
    - run: npm ci
      if: steps.npm-cache.outputs.cache-hit != 'true'
    - run: npm run build --if-present
  Test:
    runs-on: ubuntu-latest
    needs: ["Build"]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    - name: Cache node_modules
      id: npm-cache
      uses: actions/cache@v4
      with:
        path: ./node_modules
        key: npm-${{ env.NODE_VERSION }}-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-${{ env.NODE_VERSION }}-
    - run: npm ci
      if: steps.npm-cache.outputs.cache-hit != 'true'
    - run: npm test
  Release:
    runs-on: ubuntu-latest
    needs: ["Test"]
    if: ${{ github.ref == 'refs/head/main' }}
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    - name: Cache node_modules
      id: npm-cache
      uses: actions/cache@v4
      with:
        path: ./node_modules
        key: npm-${{ env.NODE_VERSION }}-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-${{ env.NODE_VERSION }}-
    - run: npm ci
      if: steps.npm-cache.outputs.cache-hit != 'true'
    - run: npm run semantic-release
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}