name: Build & Publish

on:
  push:
    branches: [ "main", "feat/initial-version" ]
  pull_request:
    branches: [ "main" ]

jobs:
  SetUp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm ci
  Build:
    runs-on: ubuntu-latest
    steps:
    - run: npm run build --if-present
  Test:
    runs-on: ubuntu-latest
    steps:
    - run: npm test